apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: secloudit-statefulset
  namespace: secloudit-namespace
spec:
  serviceName: "secloudit-service"
  replicas: 3
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
      volumes:
      - name: secloudit-volume
        emptyDir: {}